import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.7.1";

const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req: Request) => {
    if (req.method === "OPTIONS") {
        return new Response("ok", { headers: corsHeaders });
    }

    try {
        const { email, password, role, createdBy, permissions, name, phone, telegram_chat_id } = await req.json();

        const supabaseAdmin = createClient(
            Deno.env.get("SUPABASE_URL") ?? "",
            Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
        );

        // Create user in auth.users
        const { data: authData, error: authError } = await supabaseAdmin.auth.admin.createUser({
            email,
            password,
            email_confirm: true,
            user_metadata: { name } // Store name in metadata as well
        });

        if (authError) {
            return new Response(
                JSON.stringify({ error: authError.message }),
                { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
            );
        }

        // Create admin record
        const { data: adminData, error: adminError } = await supabaseAdmin
            .from("admin_users")
            .insert({
                id: authData.user.id,
                email,
                role: role || 'sub_admin', // Default to sub_admin, but allow manager
                created_by: createdBy,
                permissions: permissions || {},
                name,
                phone,
                telegram_chat_id: telegram_chat_id || null,
                is_active: !!telegram_chat_id, // Auto-activate if ID is provided manually
                // invitation_token will be auto-generated by default value in DB, 
                // but we can also set it here if we want to return it immediately without fetching again?
                // Default in DB is safest. We can select it back.
            })
            .select()
            .single();

        if (adminError) {
            // Rollback auth user creation
            await supabaseAdmin.auth.admin.deleteUser(authData.user.id);

            return new Response(
                JSON.stringify({ error: adminError.message }),
                { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
            );
        }

        return new Response(
            JSON.stringify({ success: true, admin: adminData }),
            { headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
    } catch (error) {
        return new Response(
            JSON.stringify({ error: error.message }),
            { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
    }
});
