-- Migration: Create Procurement System Tables
-- Date: 2026-02-09

-- 1. Create table for requests
CREATE TABLE IF NOT EXISTS procurement_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id UUID REFERENCES workers(id) ON DELETE CASCADE,
    object_id UUID REFERENCES cleaning_objects(id) ON DELETE CASCADE,
    item_name TEXT NOT NULL,
    photo_url TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'ordered', 'delivered')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ordered_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE
);

-- 2. Add indexes
CREATE INDEX IF NOT EXISTS idx_procurement_worker ON procurement_requests(worker_id);
CREATE INDEX IF NOT EXISTS idx_procurement_object ON procurement_requests(object_id);
CREATE INDEX IF NOT EXISTS idx_procurement_status ON procurement_requests(status);

-- 3. Enable RLS
ALTER TABLE procurement_requests ENABLE ROW LEVEL SECURITY;

-- 4. Policies
-- Workers can view and create their own requests
CREATE POLICY "Workers can view own requests" ON procurement_requests
    FOR SELECT
    USING (worker_id IN (SELECT id FROM workers WHERE telegram_user_id = auth.uid()::text OR auth.uid() IS NULL)); -- Allow public/bot for now via service role

CREATE POLICY "Workers can create requests" ON procurement_requests
    FOR INSERT
    WITH CHECK (true); -- Logic handled by bot

-- Admins can view/edit all
CREATE POLICY "Admins full access" ON procurement_requests
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);
    
-- 5. Update workers table for state management
ALTER TABLE workers 
ADD COLUMN IF NOT EXISTS bot_state TEXT,
ADD COLUMN IF NOT EXISTS temp_procurement_data JSONB;
